### ISSUE TITLE
TessJNI like API

### ISSUE THREAD

**Issue by Gerungofulus** [LuizZak/LibTessSwift#2]
Hey there!

As you might be guessing judging from my latest pull request, I'm using your framework, so let me state at first that I am super thankful that you put in the work already. However I am looking to get some more functionality into it.

# What's the problem?
For now I am recreating an API like [VTM's TessJNI](https://github.com/opensciencemap/vtm/tree/master/jni). I am basically reimplementing the very same functions, even though they might not be to "swift-like". Now I'm having to issues. For easier usability I've been subclassing your ```TessC```class. Since there is no modifier on TessC.tess, it is internal and can therefore not be accessed from classes outside of the framework, even if they're subclassing it. To replicate the functionality of TessJNI I need to access it. 
I was thinking about making another commit on the repository modifying the definition of ```Tess```, but I think there was some reasoning behind not making it public. I therefore would suggest adding that class I wrote to the Framework, but in its current state it is neither complete, nor very swift like, nor tested. On the other hand I would need to add it to the framework to properly test it. Of course I could change the modifier in the class file and then test all of it and then push it, but we're currently coding a rather big project and decided to see if the results of the code were doing what we are expecting to see if everything is working properly. On the other hand we decided to not include cocoa pods to our repository and would therefore need to modify the same file in every single working copy of our project. Besides the error that I'm not supposed to use ```tess```, I'm not getting any errors. 

# What's my idea of solving it?
So here is the deal: I would like to make ```tess``` accessible for non-framework files until my extension is properly tested and then commit it to the repository to make it available for the broader public.

# Why am I not using the already accessible ```addContour``` rather than implementing access to the Tesselator struct myself?

The TessJNI has some special use cases which I would like to cover and I believe that the already implemented handling of long float arrays instead of the handling of shorter arrays of float3 has some more performance to it, which is why I would like to offer that possibility to an API user.

**Comment by LuizZak** [comment]
Hi!

Hmm I get it, seems reasonable. I think the API indeed feels a bit closed currently because I was afraid opening up too much of the internals would make it cluttered/dangerous with pointers all exposed and stuff, but I think it's _too_ closed and opening it up would be beneficial.

For your use case, would an UnsafePointer variant of `tess` suffice? I propose we do it like this: 

1. Rename to `_tess`, keep it internal. Expose an `UnsafePointer<Tesselator>` computed property that'd expose `_tess` as a non-mutable pointer (and thus making it explicit it isn't necessary to meddle with the pointer externally from the class), like so:

```swift
public var tess: UnsafePointer<Tesselator> {
  return UnsafePointer(_tess)
}
```

So if anyone wants/needs, they can get to the struct allocated in heap and access all the goodies directly.

#### Long float arrays instead of float3 arrays

About your specific use case to use float arrays, I have to point out I changed [TESSvertex to use simd's vector_float3 to store coordinates](https://github.com/LuizZak/LibTessSwift/blob/be49a85e6a7014ed062728f8dc19424b233ce1a8/LibTessSwift/libtess2/mesh.h#L111). Does that change affect your intended use case? I can revert these changes back because I don't think they awarded that big of a performance difference as I was expecting, and if they limit the usage it's more beneficial to drop that too.

**Comment by Gerungofulus** [comment]
Hey!

I don't necessarily think that you need to revert those changes. It's just that the original file uses one big float array for all operations to add contours to the tesselator and I would like to keep that functionality for now. With the addContour function exposed by your API, I would have to convert everything I want to add to float3 first and since other developers will give me the vertices they want to add in a big combined [float] already, it doesn'T really make sense to disassemble them just to comply to your API. 
Regarding the idea with giving access to ```tess``` by making it a computed property: I dig it. Thanks for being so understanding!

**Comment by LuizZak** [comment]
Can you check my latest [`master`'s commit](https://github.com/LuizZak/LibTessSwift/commit/aeca038bb32ac0f14a08a438bc09ef7b6845ed8e)?

I've exposed the `tess` property, as well as adding variants of `addContour` and `tesselate` that work with flattened out `[TESSreal]` arrays.

**Comment by Gerungofulus** [comment]
Hey, please excuse my absence for the last couple of days as I was busy with other stuff. I'll try to check it out today. The new features sound super exciting! Thank you ❤️

If you ever happen to visit Berlin, Germany, feel free to reach out 😉

**Comment by LuizZak** [comment]
Cool! Glad this project is being of use to y'all!

Sure thing, I'll definitely give a shout out!
